version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_ambev
    ports:
      - "5432:5432" # Porta padrão do PostgreSQL
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Pass@word
      # POSTGRES_DB: DeveloperEvaluation
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume para persistência de dados

volumes:
  postgres_data:
